package com.ecommerce.config;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import javax.crypto.SecretKey;

import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.AuthorityUtils;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.filter.OncePerRequestFilter;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import jakarta.servlet.Filter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
//we added 4 dependencies in pom.xml for JWT token those are jjwt-api, jjwt-impl, jjwt-jackson and spring starter mail, so we can use those dependencies to validate the JWT token in the JwtTokenValidator class.
public class JwtTokenValidator extends OncePerRequestFilter {
       @Override
       protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
			  //get the token from the request header
			  String jwt = request.getHeader("Authorization");
			  //bearer token is a token that is used to authenticate the user, it is a string that is generated by the server and sent to the client, and the client will send this token in the request header for authentication and authorization.
			  if (jwt != null ) {
					 jwt = jwt.substring(7);
					 //validate the token
					 try {
							SecretKey key = Keys.hmacShaKeyFor(JWT_CONSTANT.SECRET_KEY.getBytes());
							Claims claims = Jwts.parserBuilder().setSigningKey(key).build().parseClaimsJws(jwt).getBody();
							String email = String.valueOf(claims.get("email"));
							String authorities = String.valueOf(claims.get("authorities"));
							List<GrantedAuthority> auths = AuthorityUtils
									.commaSeparatedStringToAuthorityList(authorities);
							Authentication authentication = new UsernamePasswordAuthenticationToken(email, null, auths);
							SecurityContextHolder.getContext().setAuthentication(authentication);
					 } catch (Exception e) {
							//if the token is invalid then we can return 401 unauthorized error
						    throw new BadCredentialsException("Invalid token");
			  }
			  filterChain.doFilter(request, response);
	   }
       }
}
